const ADD_TRAIN_SCHEDULE = 'ADD_TRAIN_SCHEDULE';
const REMOVE_TRAIN_SCHEDULE = 'REMOVE_TRAIN_SCHEDULE';
const UPDATE_TRAIN_SCHEDULE = 'UPDATE_TRAIN_SCHEDULE';

export default {
  ADD_TRAIN_SCHEDULE,
  REMOVE_TRAIN_SCHEDULE,
  UPDATE_TRAIN_SCHEDULE
};
